### ISSUE TITLE
step里面的条件，when里面的target设置为production，那我应该怎样触发production的构建呢？

### ISSUE THREAD

**Issue by ChaunceyShannon** [alicfeng/kubernetes_cicd#1]

**Comment by alicfeng** [comment]
可以通过两种方式触发
1. CLI 示例 `drone build promote octocat/hello-world 42 production`
2. CURL

**Comment by ChaunceyShannon** [comment]
谢谢大佬。

**Comment by ChaunceyShannon** [comment]
大佬，那个drone 创建 orgsecret怎么弄呢？

我的想法是，创建完镜像，push到仓库，我还需要修改另一个git的repo的yaml，那我需要存储另一个git仓库的用户密码和url，这样的话，每一个repo要3个secret实在有点蛋疼。

看到drone可以创建orgsecret，据说可以在符合条件的repo的范围内使用，但是翻了文档也没说明这个organization的名字是从哪里来的，它创建的时候又必须指定，我也没有找到可以创建organization的地方，或者查看当前organization的名字的地方。

尝试了几下，感觉是有点懵逼

```
$ drone repo ls 
gitea/demo
$ drone orgsecret add whatorg gitops_repo_user gitea
client error 401: {"message":"Not Found"}

$ drone orgsecret add gitea gitops_repo_user gitea   
client error 401: {"message":"Not Found"}

$ drone orgsecret ls 
client error 403: {"message":"Forbidden"}
```

谢谢大佬。
